version: "2"
services:
  thelounge:
    build: .
    container_name: thelounge-source
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ~/.thelounge:/config

  # Start an IRC Server for testing at irc://any_username@localhost:6667
  # inspircd:
  #   image: inspircd/inspircd-docker
  #   container_name: inspircd
  #   environment:
  #     - TZ=Europe/Zurich
  #     - INSP_ENABLE_DNSBL=no
  #   ports:
  #     - 6667:6667
  #   volumes:
  #     - ~/.inspircd/:/inspircd/conf.d/
  #   restart: unless-stopped
